static const char assembly_bootstrap_aarch64[] =
"HelloWorld:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    sub sp, sp, #32\n"
"    mov x6, x0\n"
"    bl strlen\n"
"    mov x2, x0\n"
"    mov x1, x6\n"
"    mov x16, #4\n"
"    mov x0, #1\n"
"    svc #0\n"
"\n"
"    mov x16, #1\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"strlen:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    mov w1, #0\n"
"    mov x3, x0\n"
"    cbz x3, strlenend\n"
"\n"
"strlenloop:\n"
"    ldrb w2, [x3, w1, uxtw #0]\n"
"    cmp w2, #0\n"
"    beq strlenend\n"
"    add w1, w1, #1\n"
"    b strlenloop\n"
"\n"
"strlenend:\n"
"    mov x0, x1\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"itos:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    sub sp, sp, #32\n"
"    mov x2, sp\n"
"    add x3, x2, #31\n"
"    strb wzr, [x3]\n"
"itos_loop:\n"
"    mov w4, #10\n"
"    udiv w5, w0, w4\n"
"    msub w6, w5, w4, w0\n"
"    add w6, w6, #48\n"
"    sub x3, x3, #1\n"
"    strb w6, [x3]\n"
"    mov w0, w5\n"
"    cbnz w0, itos_loop\n"
"    mov x0, x3\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"HelloWorldLine:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    sub sp, sp, #16\n"
"    mov w0, #0x0a\n"
"    strb w0, [sp]\n"
"    strb wzr, [sp, #1]\n"
"    mov x0, sp\n"
"    bl HelloWorld\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"return_statement:\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
".section __DATA,__bss\n"
".p2align 4\n"
"_str_buf: .space 4096\n"
"_btos_buf: .space 16\n"
"_str_buf0: .space 512\n"
"_str_buf1: .space 512\n"
"_str_buf2: .space 512\n"
"_str_buf3: .space 512\n"
"_str_buf4: .space 512\n"
"_str_buf5: .space 512\n"
"\n"
".text\n"
"BigWord:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x19, x20, [sp, #-16]!\n"
"    stp x21, x22, [sp, #-16]!\n"
"    mov x19, x0\n"
"    mov x20, x1\n"
"    bl strlen\n"
"    mov x21, x0\n"
"    mov x0, x20\n"
"    bl strlen\n"
"    add x2, x21, x0\n"
"    add x2, x2, #1\n"
"    adrp x3, _str_buf0@PAGE\n"
"    add x3, x3, _str_buf0@PAGEOFF\n"
"    mov x0, x3\n"
"    mov x1, x19\n"
"    mov x4, #0\n"
"BigWord_copy1:\n"
"    cmp x4, x21\n"
"    b.ge BigWord_copy2\n"
"    ldrb w5, [x1, x4]\n"
"    strb w5, [x3, x4]\n"
"    add x4, x4, #1\n"
"    b BigWord_copy1\n"
"BigWord_copy2:\n"
"    mov x1, x20\n"
"    mov x4, #0\n"
"BigWord_copy2_loop:\n"
"    ldrb w5, [x1, x4]\n"
"    cbz w5, BigWord_done\n"
"    add x6, x3, x21\n"
"    strb w5, [x6, x4]\n"
"    add x4, x4, #1\n"
"    b BigWord_copy2_loop\n"
"BigWord_done:\n"
"    add x6, x3, x21\n"
"    strb wzr, [x6, x4]\n"
"    mov x0, x3\n"
"    ldp x21, x22, [sp], #16\n"
"    ldp x19, x20, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"SmolString:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    mov x6, x0\n"
"    mov w7, w1\n"
"    mov w8, w2\n"
"    sub w9, w8, w7\n"
"    adrp x3, _str_buf1@PAGE\n"
"    add x3, x3, _str_buf1@PAGEOFF\n"
"    mov x4, #0\n"
"SmolString_loop:\n"
"    cmp w4, w9\n"
"    b.ge SmolString_end\n"
"    add x5, x7, x4\n"
"    ldrb w10, [x6, x5]\n"
"    strb w10, [x3, x4]\n"
"    add w4, w4, #1\n"
"    b SmolString_loop\n"
"SmolString_end:\n"
"    strb wzr, [x3, x4]\n"
"    mov x0, x3\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"CharAt:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    adrp x3, _str_buf2@PAGE\n"
"    add x3, x3, _str_buf2@PAGEOFF\n"
"    ldrb w4, [x0, x1]\n"
"    strb w4, [x3]\n"
"    strb wzr, [x3, #1]\n"
"    mov x0, x3\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"Change:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x23, x24, [sp, #-16]!\n"
"    stp x19, x20, [sp, #-16]!\n"
"    stp x21, x22, [sp, #-16]!\n"
"    mov x19, x0\n"
"    mov x20, x1\n"
"    mov x21, x2\n"
"    bl strlen\n"
"    mov x22, x0\n"
"    mov x0, x20\n"
"    bl strlen\n"
"    mov x23, x0\n"
"    mov x0, x21\n"
"    bl strlen\n"
"    mov x24, x0\n"
"    adrp x3, _str_buf3@PAGE\n"
"    add x3, x3, _str_buf3@PAGEOFF\n"
"    mov x4, #0\n"
"    mov x5, #0\n"
"Change_find:\n"
"    cmp x5, x22\n"
"    b.ge Change_nomatch\n"
"    mov x6, #0\n"
"Change_cmp:\n"
"    cmp x6, x23\n"
"    b.ge Change_found\n"
"    add x7, x19, x5\n"
"    add x7, x7, x6\n"
"    ldrb w8, [x7]\n"
"    ldrb w9, [x20, x6]\n"
"    cmp w8, w9\n"
"    b.ne Change_next\n"
"    add x6, x6, #1\n"
"    b Change_cmp\n"
"Change_next:\n"
"    add x5, x5, #1\n"
"    b Change_find\n"
"Change_found:\n"
"    mov x6, #0\n"
"Change_copy_before:\n"
"    cmp x6, x5\n"
"    b.ge Change_copy_new\n"
"    ldrb w8, [x19, x6]\n"
"    strb w8, [x3, x4]\n"
"    add x6, x6, #1\n"
"    add x4, x4, #1\n"
"    b Change_copy_before\n"
"Change_copy_new:\n"
"    mov x6, #0\n"
"Change_copy_new_loop:\n"
"    ldrb w8, [x21, x6]\n"
"    cbz w8, Change_copy_after\n"
"    strb w8, [x3, x4]\n"
"    add x6, x6, #1\n"
"    add x4, x4, #1\n"
"    b Change_copy_new_loop\n"
"Change_copy_after:\n"
"    add x5, x5, x23\n"
"Change_copy_after_loop:\n"
"    cmp x5, x22\n"
"    b.ge Change_done\n"
"    ldrb w8, [x19, x5]\n"
"    cbz w8, Change_done\n"
"    strb w8, [x3, x4]\n"
"    add x5, x5, #1\n"
"    add x4, x4, #1\n"
"    b Change_copy_after_loop\n"
"Change_done:\n"
"    strb wzr, [x3, x4]\n"
"    mov x0, x3\n"
"    ldp x21, x22, [sp], #16\n"
"    ldp x19, x20, [sp], #16\n"
"    ldp x23, x24, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"Change_nomatch:\n"
"    mov x0, x19\n"
"    ldp x21, x22, [sp], #16\n"
"    ldp x19, x20, [sp], #16\n"
"    ldp x23, x24, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"Clipper:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    mov x7, x0\n"
"    bl strlen\n"
"    mov x6, x0\n"
"    mov x8, #0\n"
"Clipper_lead:\n"
"    cmp x8, x6\n"
"    b.ge Clipper_trail\n"
"    ldrb w9, [x7, x8]\n"
"    cmp w9, #32\n"
"    b.lo Clipper_trail\n"
"    cmp w9, #32\n"
"    b.gt Clipper_trail\n"
"    add x8, x8, #1\n"
"    b Clipper_lead\n"
"Clipper_trail:\n"
"    cmp x6, #0\n"
"    b.eq Clipper_empty\n"
"    sub x10, x6, #1\n"
"Clipper_trail_loop:\n"
"    cmp x10, x8\n"
"    b.lo Clipper_copy\n"
"    ldrb w9, [x7, x10]\n"
"    cmp w9, #32\n"
"    b.lo Clipper_copy\n"
"    cmp w9, #32\n"
"    b.gt Clipper_copy\n"
"    sub x10, x10, #1\n"
"    b Clipper_trail_loop\n"
"Clipper_copy:\n"
"    adrp x3, _str_buf4@PAGE\n"
"    add x3, x3, _str_buf4@PAGEOFF\n"
"    mov x4, #0\n"
"Clipper_copy_loop:\n"
"    add x5, x8, x4\n"
"    cmp x5, x10\n"
"    b.gt Clipper_copy_done\n"
"    ldrb w9, [x7, x5]\n"
"    strb w9, [x3, x4]\n"
"    add x4, x4, #1\n"
"    b Clipper_copy_loop\n"
"Clipper_copy_done:\n"
"    strb wzr, [x3, x4]\n"
"    mov x0, x3\n"
"Clipper_ret:\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"Clipper_empty:\n"
"    mov x0, x7\n"
"    b Clipper_ret\n"
"\n"
"SmolStrings:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x19, x20, [sp, #-16]!\n"
"    stp x21, x22, [sp, #-16]!\n"
"    mov x19, x0\n"
"    mov x20, x1\n"
"    bl strlen\n"
"    mov x21, x0\n"
"    mov x0, x20\n"
"    bl strlen\n"
"    mov x22, x0\n"
"    adrp x3, _str_buf5@PAGE\n"
"    add x3, x3, _str_buf5@PAGEOFF\n"
"    mov x4, #0\n"
"    mov x5, #0\n"
"    mov x6, #0\n"
"SmolStrings_loop:\n"
"    cmp x5, x21\n"
"    b.ge SmolStrings_done\n"
"    mov x7, #0\n"
"SmolStrings_cmp:\n"
"    cmp x7, x22\n"
"    b.ge SmolStrings_delim\n"
"    add x8, x5, x7\n"
"    cmp x8, x21\n"
"    b.ge SmolStrings_part\n"
"    ldrb w9, [x19, x8]\n"
"    ldrb w10, [x20, x7]\n"
"    cmp w9, w10\n"
"    b.ne SmolStrings_part\n"
"    add x7, x7, #1\n"
"    b SmolStrings_cmp\n"
"SmolStrings_delim:\n"
"    cmp x4, #0\n"
"    b.eq SmolStrings_skip_sep\n"
"    mov w9, #1\n"
"    strb w9, [x3, x4]\n"
"    add x4, x4, #1\n"
"SmolStrings_skip_sep:\n"
"    add x5, x5, x22\n"
"    b SmolStrings_loop\n"
"SmolStrings_part:\n"
"    cmp x5, x21\n"
"    b.ge SmolStrings_done\n"
"    ldrb w9, [x19, x5]\n"
"    cbz w9, SmolStrings_done\n"
"    mov x7, #0\n"
"SmolStrings_cmp2:\n"
"    cmp x7, x22\n"
"    b.ge SmolStrings_delim\n"
"    add x8, x5, x7\n"
"    cmp x8, x21\n"
"    b.ge SmolStrings_part_end\n"
"    ldrb w10, [x19, x8]\n"
"    ldrb w11, [x20, x7]\n"
"    cmp w10, w11\n"
"    b.ne SmolStrings_part_end\n"
"    add x7, x7, #1\n"
"    b SmolStrings_cmp2\n"
"SmolStrings_part_end:\n"
"    strb w9, [x3, x4]\n"
"    add x4, x4, #1\n"
"    add x5, x5, #1\n"
"    b SmolStrings_part\n"
"SmolStrings_done:\n"
"    strb wzr, [x3, x4]\n"
"    mov x0, x3\n"
"    ldp x21, x22, [sp], #16\n"
"    ldp x19, x20, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"btos:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    adrp x3, _btos_buf@PAGE\n"
"    add x3, x3, _btos_buf@PAGEOFF\n"
"    cmp w0, #0\n"
"    b.eq btos_fake\n"
"    mov w1, #0x6552\n"
"    movk w1, #0x6c61, lsl #16\n"
"    str w1, [x3]\n"
"    strb wzr, [x3, #4]\n"
"    b btos_done\n"
"btos_fake:\n"
"    mov w1, #0x6146\n"
"    movk w1, #0x656b, lsl #16\n"
"    str w1, [x3]\n"
"    strb wzr, [x3, #4]\n"
"btos_done:\n"
"    mov x0, x3\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"# ---- Runtime error handlers ----\n"
"\n"
"_rt_err_oob:\n"
".asciz \"Runtime Error: Array index out of bounds\\n\"\n"
".p2align 2\n"
"_rt_err_null_str:\n"
".asciz \"Runtime Error: Null string access\\n\"\n"
".p2align 2\n"
"_rt_err_div_zero:\n"
".asciz \"Runtime Error: Division by zero\\n\"\n"
".p2align 2\n"
"\n"
"rt_error_exit:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    bl strlen\n"
"    mov x2, x0\n"
"    mov x1, x6\n"
"    mov x0, #2\n"
"    mov x16, #4\n"
"    svc #0\n"
"    mov x0, #1\n"
"    mov x16, #1\n"
"    svc #0\n"
"\n"
"rt_array_bounds_check:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    cmp w0, #0\n"
"    b.lt rt_array_oob\n"
"    cmp w0, w1\n"
"    b.ge rt_array_oob\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"rt_array_oob:\n"
"    adrp x6, _rt_err_oob@PAGE\n"
"    add x6, x6, _rt_err_oob@PAGEOFF\n"
"    mov x0, x6\n"
"    b rt_error_exit\n"
"\n"
"rt_null_str_check:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    cbnz x0, rt_null_str_ok\n"
"    adrp x6, _rt_err_null_str@PAGE\n"
"    add x6, x6, _rt_err_null_str@PAGEOFF\n"
"    mov x0, x6\n"
"    b rt_error_exit\n"
"rt_null_str_ok:\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"rt_div_zero_check:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    cbnz w0, rt_div_zero_ok\n"
"    adrp x6, _rt_err_div_zero@PAGE\n"
"    add x6, x6, _rt_err_div_zero@PAGEOFF\n"
"    mov x0, x6\n"
"    b rt_error_exit\n"
"rt_div_zero_ok:\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"# ---- Heap allocator (rent / moveOut) ----\n"
"# Block layout: [magic:4][user_size:8][flags:4][lock:4][pad:16] = 32 bytes\n"
"# User address (adr) = block_base + 32\n"
"# lock: per-block spinlock (auto-acquired on every Peek/Poke/moveOut)\n"
"\n"
"_rt_err_heap_oom:\n"
".asciz \"Runtime Error: Heap out of memory\\n\"\n"
".p2align 2\n"
"_rt_err_heap_bad_size:\n"
".asciz \"Runtime Error: Invalid heap allocation size\\n\"\n"
".p2align 2\n"
"_rt_err_heap_invalid:\n"
".asciz \"Runtime Error: Invalid heap address\\n\"\n"
".p2align 2\n"
"_rt_err_heap_double_free:\n"
".asciz \"Runtime Error: Double free (moveOut called twice)\\n\"\n"
".p2align 2\n"
"_rt_err_heap_oob:\n"
".asciz \"Runtime Error: Heap access out of bounds\\n\"\n"
".p2align 2\n"
"\n"
"rt_heap_adr_check:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    cbnz x0, rt_heap_adr_ok\n"
"    adrp x6, _rt_err_heap_invalid@PAGE\n"
"    add x6, x6, _rt_err_heap_invalid@PAGEOFF\n"
"    mov x0, x6\n"
"    b rt_error_exit\n"
"rt_heap_adr_ok:\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"rt_heap_block_lock:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x1, x2, [sp, #-16]!\n"
"    stp x3, x4, [sp, #-16]!\n"
"    sub x1, x0, #32\n"
"    add x2, x1, #16\n"
"heap_lock_retry:\n"
"    mov w3, #1\n"
"    ldaxr w4, [x2]\n"
"    cbnz w4, heap_lock_contended\n"
"    stlxr w5, w3, [x2]\n"
"    cbnz w5, heap_lock_retry\n"
"    b heap_lock_done\n"
"heap_lock_contended:\n"
"    wfe\n"
"    b heap_lock_retry\n"
"heap_lock_done:\n"
"    ldp x3, x4, [sp], #16\n"
"    ldp x1, x2, [sp], #16\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"rt_heap_block_unlock:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    stp x1, x2, [sp, #-16]!\n"
"    sub x1, x0, #32\n"
"    add x1, x1, #16\n"
"    stlr wzr, [x1]\n"
"    dsb ish\n"
"    sev\n"
"    ldp x1, x2, [sp], #16\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"rt_heap_bounds_check:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x19, x20, [sp, #-16]!\n"
"    stp x21, x22, [sp, #-16]!\n"
"    mov x20, x1\n"
"    mov x21, x2\n"
"    cbz x0, rt_heap_bounds_invalid\n"
"    sub x19, x0, #32\n"
"    ldr w3, [x19]\n"
"    mov w4, #0xBEEF\n"
"    movk w4, #0xDEAD, lsl #16\n"
"    cmp w3, w4\n"
"    b.ne rt_heap_bounds_invalid\n"
"    ldr w3, [x19, #12]\n"
"    cbz w3, rt_heap_bounds_invalid\n"
"    ldr x4, [x19, #4]\n"
"    add x5, x20, x21\n"
"    cmp x5, x4\n"
"    b.gt rt_heap_bounds_oob\n"
"    ldp x21, x22, [sp], #16\n"
"    ldp x19, x20, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"rt_heap_bounds_oob:\n"
"    adrp x6, _rt_err_heap_oob@PAGE\n"
"    add x6, x6, _rt_err_heap_oob@PAGEOFF\n"
"    mov x0, x6\n"
"    b rt_error_exit\n"
"rt_heap_bounds_invalid:\n"
"    adrp x6, _rt_err_heap_invalid@PAGE\n"
"    add x6, x6, _rt_err_heap_invalid@PAGEOFF\n"
"    mov x0, x6\n"
"    b rt_error_exit\n"
"\n"
"rentMul:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    mul w0, w0, w1\n"
"    cbz w0, rent_bad_size\n"
"    cmp w0, #1048576\n"
"    b.gt rent_bad_size\n"
"    bl rent\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"rent:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x19, x20, [sp, #-16]!\n"
"    stp x21, x22, [sp, #-16]!\n"
"    cbz w0, rent_bad_size\n"
"    cmp w0, #1048576\n"
"    b.gt rent_bad_size\n"
"    mov x19, x0\n"
"    add x0, x0, #32\n"
"    bl _malloc\n"
"    cbz x0, rent_oom\n"
"    mov x21, x0\n"
"    mov w1, #0xBEEF\n"
"    movk w1, #0xDEAD, lsl #16\n"
"    str w1, [x21]\n"
"    str x19, [x21, #4]\n"
"    mov w1, #1\n"
"    str w1, [x21, #12]\n"
"    str wzr, [x21, #16]\n"
"    add x1, x21, #32\n"
"    mov x2, x19\n"
"rent_zero:\n"
"    cbz x2, rent_done\n"
"    strb wzr, [x1], #1\n"
"    sub x2, x2, #1\n"
"    b rent_zero\n"
"rent_done:\n"
"    add x0, x21, #32\n"
"    ldp x21, x22, [sp], #16\n"
"    ldp x19, x20, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"rent_bad_size:\n"
"    adrp x6, _rt_err_heap_bad_size@PAGE\n"
"    add x6, x6, _rt_err_heap_bad_size@PAGEOFF\n"
"    mov x0, x6\n"
"    b rt_error_exit\n"
"rent_oom:\n"
"    adrp x6, _rt_err_heap_oom@PAGE\n"
"    add x6, x6, _rt_err_heap_oom@PAGEOFF\n"
"    mov x0, x6\n"
"    b rt_error_exit\n"
"\n"
"moveOut:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x19, x20, [sp, #-16]!\n"
"    stp x21, x22, [sp, #-16]!\n"
"    cbz x0, moveOut_invalid\n"
"    mov x21, x0\n"
"    sub x19, x0, #32\n"
"    ldr w1, [x19]\n"
"    mov w2, #0xBEEF\n"
"    movk w2, #0xDEAD, lsl #16\n"
"    cmp w1, w2\n"
"    b.ne moveOut_invalid\n"
"    mov x0, x21\n"
"    bl rt_heap_block_lock\n"
"    ldr w1, [x19, #12]\n"
"    cbz w1, moveOut_double_unlock\n"
"    str wzr, [x19, #12]\n"
"    ldr x2, [x19, #4]\n"
"    mov x1, x21\n"
"moveOut_wipe:\n"
"    cbz x2, moveOut_unmap\n"
"    strb wzr, [x1], #1\n"
"    sub x2, x2, #1\n"
"    b moveOut_wipe\n"
"moveOut_unmap:\n"
"    mov x0, x21\n"
"    bl rt_heap_block_unlock\n"
"    mov x0, x19\n"
"    bl _free\n"
"    mov x0, #0\n"
"    ldp x21, x22, [sp], #16\n"
"    ldp x19, x20, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"moveOut_invalid:\n"
"    adrp x6, _rt_err_heap_invalid@PAGE\n"
"    add x6, x6, _rt_err_heap_invalid@PAGEOFF\n"
"    mov x0, x6\n"
"    b rt_error_exit\n"
"moveOut_double_unlock:\n"
"    mov x0, x21\n"
"    bl rt_heap_block_unlock\n"
"moveOut_double:\n"
"    adrp x6, _rt_err_heap_double_free@PAGE\n"
"    add x6, x6, _rt_err_heap_double_free@PAGEOFF\n"
"    mov x0, x6\n"
"    b rt_error_exit\n"
"\n"
"PeekByte:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x19, x20, [sp, #-16]!\n"
"    mov w2, #1\n"
"    bl rt_heap_bounds_check\n"
"    mov x19, x0\n"
"    bl rt_heap_block_lock\n"
"    sub x2, x19, #32\n"
"    ldr w3, [x2, #12]\n"
"    cbz w3, rt_heap_block_dead\n"
"    add x1, x19, x1\n"
"    ldrb w0, [x1]\n"
"    mov x20, x0\n"
"    mov x0, x19\n"
"    bl rt_heap_block_unlock\n"
"    mov w0, w20\n"
"    ldp x19, x20, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"PokeByte:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x19, x20, [sp, #-16]!\n"
"    stp x21, x22, [sp, #-16]!\n"
"    mov x21, x2\n"
"    mov w2, #1\n"
"    bl rt_heap_bounds_check\n"
"    mov x19, x0\n"
"    bl rt_heap_block_lock\n"
"    sub x2, x19, #32\n"
"    ldr w3, [x2, #12]\n"
"    cbz w3, rt_heap_block_dead\n"
"    add x1, x19, x1\n"
"    strb w21, [x1]\n"
"    mov x0, x19\n"
"    bl rt_heap_block_unlock\n"
"    mov w0, #0\n"
"    ldp x21, x22, [sp], #16\n"
"    ldp x19, x20, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"PeekInt:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x19, x20, [sp, #-16]!\n"
"    mov w2, #4\n"
"    bl rt_heap_bounds_check\n"
"    mov x19, x0\n"
"    bl rt_heap_block_lock\n"
"    sub x2, x19, #32\n"
"    ldr w3, [x2, #12]\n"
"    cbz w3, rt_heap_block_dead\n"
"    add x1, x19, x1\n"
"    ldr w0, [x1]\n"
"    mov x20, x0\n"
"    mov x0, x19\n"
"    bl rt_heap_block_unlock\n"
"    mov w0, w20\n"
"    ldp x19, x20, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"PokeInt:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x19, x20, [sp, #-16]!\n"
"    stp x21, x22, [sp, #-16]!\n"
"    mov x21, x2\n"
"    mov w2, #4\n"
"    bl rt_heap_bounds_check\n"
"    mov x19, x0\n"
"    bl rt_heap_block_lock\n"
"    sub x2, x19, #32\n"
"    ldr w3, [x2, #12]\n"
"    cbz w3, rt_heap_block_dead\n"
"    add x1, x19, x1\n"
"    str w21, [x1]\n"
"    mov x0, x19\n"
"    bl rt_heap_block_unlock\n"
"    mov w0, #0\n"
"    ldp x21, x22, [sp], #16\n"
"    ldp x19, x20, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"AddInt:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x19, x20, [sp, #-16]!\n"
"    stp x21, x22, [sp, #-16]!\n"
"    mov x21, x2\n"
"    mov w2, #4\n"
"    bl rt_heap_bounds_check\n"
"    mov x19, x0\n"
"    bl rt_heap_block_lock\n"
"    sub x2, x19, #32\n"
"    ldr w3, [x2, #12]\n"
"    cbz w3, rt_heap_block_dead\n"
"    add x1, x19, x1\n"
"    ldr w0, [x1]\n"
"    add w0, w0, w21\n"
"    str w0, [x1]\n"
"    mov x20, x0\n"
"    mov x0, x19\n"
"    bl rt_heap_block_unlock\n"
"    mov w0, w20\n"
"    ldp x21, x22, [sp], #16\n"
"    ldp x19, x20, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"rt_heap_block_dead:\n"
"    mov x0, x19\n"
"    bl rt_heap_block_unlock\n"
"    adrp x6, _rt_err_heap_invalid@PAGE\n"
"    add x6, x6, _rt_err_heap_invalid@PAGEOFF\n"
"    mov x0, x6\n"
"    b rt_error_exit\n"
"\n"
".extern _memcpy\n"
".extern _memset\n"
"\n"
"Memcpy:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x19, x20, [sp, #-16]!\n"
"    stp x21, x22, [sp, #-16]!\n"
"    mov x19, x0\n"
"    mov x20, x1\n"
"    mov w21, w2\n"
"    cbz w21, memcpy_done\n"
"    mov w1, #0\n"
"    mov w2, w21\n"
"    mov x0, x19\n"
"    bl rt_heap_bounds_check\n"
"    mov x0, x20\n"
"    mov w1, #0\n"
"    mov w2, w21\n"
"    bl rt_heap_bounds_check\n"
"    mov x0, x19\n"
"    mov x1, x20\n"
"    mov x2, x21\n"
"    bl _memcpy\n"
"memcpy_done:\n"
"    mov w0, #0\n"
"    ldp x21, x22, [sp], #16\n"
"    ldp x19, x20, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"Memset:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x19, x20, [sp, #-16]!\n"
"    stp x21, x22, [sp, #-16]!\n"
"    mov x21, x0\n"
"    mov w20, w1\n"
"    mov w22, w2\n"
"    cbz w22, memset_done\n"
"    mov w1, #0\n"
"    mov w2, w22\n"
"    mov x0, x21\n"
"    bl rt_heap_bounds_check\n"
"    mov x0, x21\n"
"    bl rt_heap_block_lock\n"
"    sub x19, x21, #32\n"
"    ldr w3, [x19, #12]\n"
"    cbz w3, rt_heap_block_dead\n"
"    mov x1, x21\n"
"    mov w2, w20\n"
"    mov w3, w22\n"
"memset_loop:\n"
"    cbz w3, memset_unlock\n"
"    strb w2, [x1], #1\n"
"    sub w3, w3, #1\n"
"    b memset_loop\n"
"memset_unlock:\n"
"    mov x0, x21\n"
"    bl rt_heap_block_unlock\n"
"memset_done:\n"
"    mov w0, #0\n"
"    ldp x21, x22, [sp], #16\n"
"    ldp x19, x20, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"RentGrow:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x19, x20, [sp, #-16]!\n"
"    stp x21, x22, [sp, #-16]!\n"
"    stp x23, x24, [sp, #-16]!\n"
"    cbz x0, rentgrow_invalid\n"
"    mov x23, x0\n"
"    mov w24, w1\n"
"    cbz w24, rentgrow_bad_size\n"
"    cmp w24, #1048576\n"
"    b.gt rentgrow_bad_size\n"
"    sub x19, x23, #32\n"
"    ldr w1, [x19]\n"
"    mov w2, #0xBEEF\n"
"    movk w2, #0xDEAD, lsl #16\n"
"    cmp w1, w2\n"
"    b.ne rentgrow_invalid\n"
"    ldr x22, [x19, #4]\n"
"    mov w0, w24\n"
"    bl rent\n"
"    mov x21, x0\n"
"    mov x2, x22\n"
"    mov x3, x24\n"
"    cmp x2, x3\n"
"    b.le rentgrow_copy_len_ok\n"
"    mov x2, x3\n"
"rentgrow_copy_len_ok:\n"
"    cbz x2, rentgrow_free_old\n"
"    mov x0, x21\n"
"    mov x1, x23\n"
"    bl _memcpy\n"
"rentgrow_free_old:\n"
"    mov x0, x23\n"
"    bl moveOut\n"
"    mov x0, x21\n"
"    b rentgrow_done\n"
"rentgrow_invalid:\n"
"    adrp x6, _rt_err_heap_invalid@PAGE\n"
"    add x6, x6, _rt_err_heap_invalid@PAGEOFF\n"
"    mov x0, x6\n"
"    b rt_error_exit\n"
"rentgrow_bad_size:\n"
"    adrp x6, _rt_err_heap_bad_size@PAGE\n"
"    add x6, x6, _rt_err_heap_bad_size@PAGEOFF\n"
"    mov x0, x6\n"
"    b rt_error_exit\n"
"rentgrow_done:\n"
"    ldp x23, x24, [sp], #16\n"
"    ldp x21, x22, [sp], #16\n"
"    ldp x19, x20, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"AdrLo:\n"
"    ret\n"
"\n"
"AdrHi:\n"
"    lsr x0, x0, #32\n"
"    ret\n"
"\n"
"# ---- Threading (dupe / join) and timer ----\n"
".extern _pthread_create\n"
".extern _pthread_attr_init\n"
".extern _pthread_attr_setstacksize\n"
".extern _pthread_attr_destroy\n"
".extern _malloc\n"
".extern _free\n"
".extern _gettimeofday\n"
"\n"
".section __DATA,__data\n"
".align 3\n"
"rt_dupe_count:\n"
"    .quad 0\n"
"rt_dupe_slots:\n"
"    .space 512\n"
"rt_dupe_done:\n"
"    .space 64\n"
"\n"
".text\n"
"\n"
"timer:\n"
"    stp x29, x30, [sp, #-32]!\n"
"    mov x29, sp\n"
"    add x0, sp, #16\n"
"    mov x1, xzr\n"
"    bl _gettimeofday\n"
"    ldr x2, [sp, #16]\n"
"    ldr w3, [sp, #24]\n"
"    mov x4, #1000\n"
"    mul x5, x2, x4\n"
"    mov x4, #1000\n"
"    mul x5, x5, x4\n"
"    add x0, x5, x3\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #32\n"
"    ret\n"
"\n"
"rt_dupe_trampoline:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x19, x20, [sp, #-16]!\n"
"    stp x21, x22, [sp, #-16]!\n"
"    mov x19, x0\n"
"    ldr x20, [x19]\n"
"    ldr x0, [x19, #8]\n"
"    blr x20\n"
"    ldr x22, [x19, #16]\n"
"    adrp x21, rt_dupe_done@PAGE\n"
"    add x21, x21, rt_dupe_done@PAGEOFF\n"
"    add x21, x21, x22\n"
"    mov w1, #1\n"
"    strb w1, [x21]\n"
"    mov x0, x19\n"
"    bl _free\n"
"    mov x0, #0\n"
"    ldp x21, x22, [sp], #16\n"
"    ldp x19, x20, [sp], #16\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"rt_dupe_spawn:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x19, x20, [sp, #-16]!\n"
"    stp x21, x22, [sp, #-16]!\n"
"    stp x23, x24, [sp, #-16]!\n"
"    mov x19, x0\n"
"    mov x20, x1\n"
"    sub sp, sp, #64\n"
"    mov x23, sp\n"
"    mov x0, x23\n"
"    bl _pthread_attr_init\n"
"    mov x0, x23\n"
"    movz x1, #0\n"
"    movk x1, #0x80, lsl #16\n"
"    bl _pthread_attr_setstacksize\n"
"    mov x0, #24\n"
"    bl _malloc\n"
"    mov x21, x0\n"
"    cbz x21, rt_dupe_spawn_fail\n"
"    str x19, [x21]\n"
"    str x20, [x21, #8]\n"
"    adrp x0, rt_dupe_count@PAGE\n"
"    add x0, x0, rt_dupe_count@PAGEOFF\n"
"    ldr x22, [x0]\n"
"    cmp x22, #64\n"
"    b.ge rt_dupe_spawn_fail\n"
"    add x9, x22, #1\n"
"    str x9, [x0]\n"
"    str x22, [x21, #16]\n"
"    adrp x1, rt_dupe_slots@PAGE\n"
"    add x1, x1, rt_dupe_slots@PAGEOFF\n"
"    lsl x2, x22, #3\n"
"    add x1, x1, x2\n"
"    mov x0, x1\n"
"    mov x1, x23\n"
"    adrp x2, rt_dupe_trampoline@PAGE\n"
"    add x2, x2, rt_dupe_trampoline@PAGEOFF\n"
"    mov x3, x21\n"
"    bl _pthread_create\n"
"    mov w24, w0\n"
"    mov x0, x23\n"
"    bl _pthread_attr_destroy\n"
"    cbnz w24, rt_dupe_spawn_fail\n"
"    mov w0, w22\n"
"    b rt_dupe_spawn_done\n"
"rt_dupe_spawn_fail:\n"
"    cbz x23, rt_dupe_spawn_fail_free\n"
"    mov x0, x23\n"
"    bl _pthread_attr_destroy\n"
"rt_dupe_spawn_fail_free:\n"
"    cbz x21, rt_dupe_spawn_done\n"
"    mov x0, x21\n"
"    bl _free\n"
"    mov w0, #-1\n"
"rt_dupe_spawn_done:\n"
"    add sp, sp, #64\n"
"    ldp x23, x24, [sp], #16\n"
"    ldp x21, x22, [sp], #16\n"
"    ldp x19, x20, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"join:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x19, x20, [sp, #-16]!\n"
"    mov w19, w0\n"
"    cmp w19, #0\n"
"    blt join_bad\n"
"    cmp w19, #64\n"
"    b.ge join_bad\n"
"    adrp x20, rt_dupe_done@PAGE\n"
"    add x20, x20, rt_dupe_done@PAGEOFF\n"
"    add x20, x20, x19\n"
"join_wait:\n"
"    ldrb w1, [x20]\n"
"    cbz w1, join_wait\n"
"    mov w0, #0\n"
"    b join_done\n"
"join_bad:\n"
"    mov w0, #-1\n"
"join_done:\n"
"    ldp x19, x20, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n";
#define assembly_bootstrap_aarch64_len (sizeof(assembly_bootstrap_aarch64) - 1)
