static const char assembly_bootstrap_x86_64[] =
"HelloWorld:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    sub rsp, 32\n"
"    mov rbx, rdi\n"
"    call strlen\n"
"    mov rdx, rax\n"
"    mov rsi, rbx\n"
"    mov rdi, 1\n"
"    mov rax, 0x2000004\n"
"    syscall\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"strlen:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    xor eax, eax\n"
"    test rdi, rdi\n"
"    jz strlenend\n"
"    mov rcx, rdi\n"
"strlenloop:\n"
"    movzx edx, byte ptr [rcx + rax]\n"
"    test dl, dl\n"
"    jz strlenend\n"
"    inc eax\n"
"    jmp strlenloop\n"
"strlenend:\n"
"    movsxd rax, eax\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"itos:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    lea r8, [rip + _itos_buf + 31]\n"
"    mov byte ptr [r8], 0\n"
"    mov eax, edi\n"
"itos_loop:\n"
"    xor edx, edx\n"
"    mov ecx, 10\n"
"    div ecx\n"
"    add dl, 48\n"
"    dec r8\n"
"    mov byte ptr [r8], dl\n"
"    test eax, eax\n"
"    jnz itos_loop\n"
"    mov rax, r8\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"HelloWorldLine:\n"
"    lea rdi, [rip + _newline]\n"
"    call HelloWorld\n"
"    ret\n"
"\n"
"return_statement:\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
".section __DATA,__bss\n"
".p2align 4\n"
"_str_buf: .space 4096\n"
"_btos_buf: .space 16\n"
"_itos_buf: .space 32\n"
"_str_buf0: .space 512\n"
"_str_buf1: .space 512\n"
"_str_buf2: .space 512\n"
"_str_buf3: .space 512\n"
"_str_buf4: .space 512\n"
"_str_buf5: .space 512\n"
"\n"
".text\n"
"BigWord:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    push r12\n"
"    push r13\n"
"    push r14\n"
"    push r15\n"
"    mov r12, rdi\n"
"    mov r13, rsi\n"
"    call strlen\n"
"    mov r14, rax\n"
"    mov rdi, r13\n"
"    call strlen\n"
"    lea r15, [rip + _str_buf0]\n"
"    mov rdi, r15\n"
"    mov rsi, r12\n"
"    xor ecx, ecx\n"
"BigWord_copy1:\n"
"    cmp rcx, r14\n"
"    jge BigWord_copy2\n"
"    movzx eax, byte ptr [rsi + rcx]\n"
"    mov byte ptr [r15 + rcx], al\n"
"    inc rcx\n"
"    jmp BigWord_copy1\n"
"BigWord_copy2:\n"
"    mov rsi, r13\n"
"    xor ecx, ecx\n"
"BigWord_copy2_loop:\n"
"    movzx eax, byte ptr [rsi + rcx]\n"
"    test al, al\n"
"    jz BigWord_done\n"
"    lea rax, [r15 + r14]\n"
"    mov byte ptr [rax + rcx], al\n"
"    inc rcx\n"
"    jmp BigWord_copy2_loop\n"
"BigWord_done:\n"
"    lea rax, [r15 + r14]\n"
"    mov byte ptr [rax + rcx], 0\n"
"    mov rax, r15\n"
"    pop r15\n"
"    pop r14\n"
"    pop r13\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"SmolString:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    push r12\n"
"    push r13\n"
"    push r15\n"
"    mov r12, rdi\n"
"    mov ebx, esi\n"
"    mov r13d, edx\n"
"    sub r13d, ebx\n"
"    lea r15, [rip + _str_buf1]\n"
"    xor ecx, ecx\n"
"SmolString_loop:\n"
"    cmp ecx, r13d\n"
"    jge SmolString_end\n"
"    lea eax, [rbx + rcx]\n"
"    movzx eax, byte ptr [r12 + rax]\n"
"    mov byte ptr [r15 + rcx], al\n"
"    inc ecx\n"
"    jmp SmolString_loop\n"
"SmolString_end:\n"
"    mov byte ptr [r15 + rcx], 0\n"
"    mov rax, r15\n"
"    pop r15\n"
"    pop r13\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"CharAt:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    lea rax, [rip + _str_buf2]\n"
"    movzx ecx, byte ptr [rdi + rsi]\n"
"    mov byte ptr [rax], cl\n"
"    mov byte ptr [rax + 1], 0\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"Change:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    push r12\n"
"    push r13\n"
"    push r14\n"
"    push r15\n"
"    mov r12, rdi\n"
"    mov r13, rsi\n"
"    mov r14, rdx\n"
"    mov rdi, r12\n"
"    call strlen\n"
"    mov rbx, rax\n"
"    mov rdi, r13\n"
"    call strlen\n"
"    mov r15, rax\n"
"    mov rdi, r14\n"
"    call strlen\n"
"    push rax\n"
"    lea r8, [rip + _str_buf3]\n"
"    xor ecx, ecx\n"
"    xor edx, edx\n"
"Change_find:\n"
"    cmp rdx, rbx\n"
"    jge Change_nomatch\n"
"    xor r9, r9\n"
"Change_cmp:\n"
"    cmp r9, r15\n"
"    jge Change_found\n"
"    lea rax, [r12 + rdx]\n"
"    add rax, r9\n"
"    movzx eax, byte ptr [rax]\n"
"    movzx r10d, byte ptr [r13 + r9]\n"
"    cmp eax, r10d\n"
"    jne Change_next\n"
"    inc r9\n"
"    jmp Change_cmp\n"
"Change_next:\n"
"    inc rdx\n"
"    jmp Change_find\n"
"Change_found:\n"
"    xor r9, r9\n"
"Change_copy_before:\n"
"    cmp r9, rdx\n"
"    jge Change_copy_new\n"
"    movzx eax, byte ptr [r12 + r9]\n"
"    mov byte ptr [r8 + rcx], al\n"
"    inc r9\n"
"    inc rcx\n"
"    jmp Change_copy_before\n"
"Change_copy_new:\n"
"    xor r9, r9\n"
"Change_copy_new_loop:\n"
"    movzx eax, byte ptr [r14 + r9]\n"
"    test al, al\n"
"    jz Change_copy_after\n"
"    mov byte ptr [r8 + rcx], al\n"
"    inc r9\n"
"    inc rcx\n"
"    jmp Change_copy_new_loop\n"
"Change_copy_after:\n"
"    add rdx, r15\n"
"Change_copy_after_loop:\n"
"    cmp rdx, rbx\n"
"    jge Change_done\n"
"    movzx eax, byte ptr [r12 + rdx]\n"
"    test al, al\n"
"    jz Change_done\n"
"    mov byte ptr [r8 + rcx], al\n"
"    inc rdx\n"
"    inc rcx\n"
"    jmp Change_copy_after_loop\n"
"Change_done:\n"
"    mov byte ptr [r8 + rcx], 0\n"
"    mov rax, r8\n"
"    add rsp, 8\n"
"    pop r15\n"
"    pop r14\n"
"    pop r13\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"Change_nomatch:\n"
"    mov rax, r12\n"
"    add rsp, 8\n"
"    pop r15\n"
"    pop r14\n"
"    pop r13\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"Clipper:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    push r12\n"
"    push r13\n"
"    push r14\n"
"    push r15\n"
"    mov r12, rdi\n"
"    call strlen\n"
"    mov rbx, rax\n"
"    xor r13, r13\n"
"Clipper_lead:\n"
"    cmp r13, rbx\n"
"    jge Clipper_trail\n"
"    movzx eax, byte ptr [r12 + r13]\n"
"    cmp eax, 32\n"
"    jb Clipper_trail\n"
"    cmp eax, 32\n"
"    ja Clipper_trail\n"
"    inc r13\n"
"    jmp Clipper_lead\n"
"Clipper_trail:\n"
"    cmp rbx, 0\n"
"    je Clipper_empty\n"
"    lea r14, [rbx - 1]\n"
"Clipper_trail_loop:\n"
"    cmp r14, r13\n"
"    jb Clipper_copy\n"
"    movzx eax, byte ptr [r12 + r14]\n"
"    cmp eax, 32\n"
"    jb Clipper_copy\n"
"    cmp eax, 32\n"
"    ja Clipper_copy\n"
"    dec r14\n"
"    jmp Clipper_trail_loop\n"
"Clipper_copy:\n"
"    lea r15, [rip + _str_buf4]\n"
"    xor ecx, ecx\n"
"Clipper_copy_loop:\n"
"    lea rax, [r13 + rcx]\n"
"    cmp rax, r14\n"
"    jg Clipper_copy_done\n"
"    movzx eax, byte ptr [r12 + rax]\n"
"    mov byte ptr [r15 + rcx], al\n"
"    inc rcx\n"
"    jmp Clipper_copy_loop\n"
"Clipper_copy_done:\n"
"    mov byte ptr [r15 + rcx], 0\n"
"    mov rax, r15\n"
"Clipper_ret:\n"
"    pop r15\n"
"    pop r14\n"
"    pop r13\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"Clipper_empty:\n"
"    mov rax, r12\n"
"    jmp Clipper_ret\n"
"\n"
"SmolStrings:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    push r12\n"
"    push r13\n"
"    push r14\n"
"    push r15\n"
"    mov r12, rdi\n"
"    mov r13, rsi\n"
"    call strlen\n"
"    mov r14, rax\n"
"    mov rdi, r13\n"
"    call strlen\n"
"    push rax\n"
"    lea r15, [rip + _str_buf5]\n"
"    xor ecx, ecx\n"
"    xor edx, edx\n"
"    xor ebx, ebx\n"
"SmolStrings_loop:\n"
"    cmp rdx, r14\n"
"    jge SmolStrings_done\n"
"    xor r8, r8\n"
"SmolStrings_cmp:\n"
"    cmp r8, qword ptr [rsp]\n"
"    jge SmolStrings_delim\n"
"    lea rax, [rdx + r8]\n"
"    cmp rax, r14\n"
"    jge SmolStrings_part\n"
"    movzx eax, byte ptr [r12 + rax]\n"
"    movzx r9d, byte ptr [r13 + r8]\n"
"    cmp eax, r9d\n"
"    jne SmolStrings_part\n"
"    inc r8\n"
"    jmp SmolStrings_cmp\n"
"SmolStrings_delim:\n"
"    cmp ecx, 0\n"
"    je SmolStrings_skip_sep\n"
"    mov byte ptr [r15 + rcx], 1\n"
"    inc ecx\n"
"SmolStrings_skip_sep:\n"
"    add rdx, qword ptr [rsp]\n"
"    jmp SmolStrings_loop\n"
"SmolStrings_part:\n"
"    cmp rdx, r14\n"
"    jge SmolStrings_done\n"
"    movzx eax, byte ptr [r12 + rdx]\n"
"    test al, al\n"
"    jz SmolStrings_done\n"
"    xor r8, r8\n"
"SmolStrings_cmp2:\n"
"    cmp r8, qword ptr [rsp]\n"
"    jge SmolStrings_delim\n"
"    lea rax, [rdx + r8]\n"
"    cmp rax, r14\n"
"    jge SmolStrings_part_end\n"
"    movzx eax, byte ptr [r12 + rax]\n"
"    movzx r9d, byte ptr [r13 + r8]\n"
"    cmp eax, r9d\n"
"    jne SmolStrings_part_end\n"
"    inc r8\n"
"    jmp SmolStrings_cmp2\n"
"SmolStrings_part_end:\n"
"    movzx eax, byte ptr [r12 + rdx]\n"
"    mov byte ptr [r15 + rcx], al\n"
"    inc ecx\n"
"    inc rdx\n"
"    jmp SmolStrings_part\n"
"SmolStrings_done:\n"
"    mov byte ptr [r15 + rcx], 0\n"
"    mov rax, r15\n"
"    add rsp, 8\n"
"    pop r15\n"
"    pop r14\n"
"    pop r13\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"btos:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    lea rax, [rip + _btos_buf]\n"
"    cmp edi, 0\n"
"    je btos_fake\n"
"    mov dword ptr [rax], 0x6c616552\n"
"    mov byte ptr [rax + 4], 0\n"
"    jmp btos_done\n"
"btos_fake:\n"
"    mov dword ptr [rax], 0x656b6146\n"
"    mov byte ptr [rax + 4], 0\n"
"btos_done:\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"# ---- Runtime error handlers ----\n"
"\n"
"_rt_err_oob:\n"
".asciz \"Runtime Error: Array index out of bounds\\n\"\n"
".p2align 2\n"
"_rt_err_null_str:\n"
".asciz \"Runtime Error: Null string access\\n\"\n"
".p2align 2\n"
"_rt_err_div_zero:\n"
".asciz \"Runtime Error: Division by zero\\n\"\n"
".p2align 2\n"
"\n"
"rt_error_exit:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    mov rbx, rdi\n"
"    mov rdi, rbx\n"
"    call strlen\n"
"    mov rdx, rax\n"
"    mov rsi, rbx\n"
"    mov rdi, 2\n"
"    mov rax, 0x2000004\n"
"    syscall\n"
"    mov rdi, 1\n"
"    mov rax, 0x2000001\n"
"    syscall\n"
"\n"
"rt_array_bounds_check:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    cmp edi, 0\n"
"    jl rt_array_oob\n"
"    cmp edi, esi\n"
"    jge rt_array_oob\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"rt_array_oob:\n"
"    lea rdi, [rip + _rt_err_oob]\n"
"    jmp rt_error_exit\n"
"\n"
"rt_null_str_check:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    test rdi, rdi\n"
"    jnz rt_null_str_ok\n"
"    lea rdi, [rip + _rt_err_null_str]\n"
"    jmp rt_error_exit\n"
"rt_null_str_ok:\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"rt_div_zero_check:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    test edi, edi\n"
"    jnz rt_div_zero_ok\n"
"    lea rdi, [rip + _rt_err_div_zero]\n"
"    jmp rt_error_exit\n"
"rt_div_zero_ok:\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"# ---- Heap allocator (rent / moveOut) ----\n"
"# Block layout: [magic:4][user_size:8][flags:4][lock:4][pad:16] = 32 bytes\n"
"# User address (adr) = block_base + 32\n"
"# lock: per-block spinlock (auto-acquired on every Peek/Poke/moveOut)\n"
"\n"
"_rt_err_heap_oom:\n"
".asciz \"Runtime Error: Heap out of memory\\n\"\n"
".p2align 2\n"
"_rt_err_heap_bad_size:\n"
".asciz \"Runtime Error: Invalid heap allocation size\\n\"\n"
".p2align 2\n"
"_rt_err_heap_invalid:\n"
".asciz \"Runtime Error: Invalid heap address\\n\"\n"
".p2align 2\n"
"_rt_err_heap_double_free:\n"
".asciz \"Runtime Error: Double free (moveOut called twice)\\n\"\n"
".p2align 2\n"
"_rt_err_heap_oob:\n"
".asciz \"Runtime Error: Heap access out of bounds\\n\"\n"
".p2align 2\n"
"\n"
"rt_heap_adr_check:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    test rdi, rdi\n"
"    jnz rt_heap_adr_ok\n"
"    lea rdi, [rip + _rt_err_heap_invalid]\n"
"    jmp rt_error_exit\n"
"rt_heap_adr_ok:\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"rt_heap_block_lock:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    lea rbx, [rdi - 16]\n"
"heap_lock_retry:\n"
"    mov ecx, 1\n"
"    xor eax, eax\n"
"    lock cmpxchg dword ptr [rbx], ecx\n"
"    jnz heap_lock_contended\n"
"    jmp heap_lock_done\n"
"heap_lock_contended:\n"
"    pause\n"
"    jmp heap_lock_retry\n"
"heap_lock_done:\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"rt_heap_block_unlock:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    lea rax, [rdi - 16]\n"
"    mov dword ptr [rax], 0\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"rt_heap_bounds_check:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    push r12\n"
"    push r13\n"
"    mov r12, rsi\n"
"    mov r13, rdx\n"
"    test rdi, rdi\n"
"    jz rt_heap_bounds_invalid\n"
"    lea rbx, [rdi - 32]\n"
"    mov eax, dword ptr [rbx]\n"
"    cmp eax, 0xDEADBEEF\n"
"    jne rt_heap_bounds_invalid\n"
"    mov eax, dword ptr [rbx + 12]\n"
"    test eax, eax\n"
"    jz rt_heap_bounds_invalid\n"
"    mov rax, qword ptr [rbx + 4]\n"
"    lea rcx, [r12 + r13]\n"
"    cmp rcx, rax\n"
"    jg rt_heap_bounds_oob\n"
"    mov rax, rdi\n"
"    pop r13\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"rt_heap_bounds_oob:\n"
"    lea rdi, [rip + _rt_err_heap_oob]\n"
"    jmp rt_error_exit\n"
"rt_heap_bounds_invalid:\n"
"    lea rdi, [rip + _rt_err_heap_invalid]\n"
"    jmp rt_error_exit\n"
"\n"
"rentMul:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    imul edi, esi\n"
"    test edi, edi\n"
"    jz rent_bad_size\n"
"    cmp edi, 1048576\n"
"    jg rent_bad_size\n"
"    call rent\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"rent:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    push r12\n"
"    push r13\n"
"    test edi, edi\n"
"    jz rent_bad_size\n"
"    cmp edi, 1048576\n"
"    jg rent_bad_size\n"
"    movsxd rbx, edi\n"
"    lea rdi, [rbx + 32]\n"
"    call _malloc\n"
"    test rax, rax\n"
"    jz rent_oom\n"
"    mov r12, rax\n"
"    mov dword ptr [r12], 0xDEADBEEF\n"
"    mov qword ptr [r12 + 4], rbx\n"
"    mov dword ptr [r12 + 12], 1\n"
"    mov dword ptr [r12 + 16], 0\n"
"    lea r13, [r12 + 32]\n"
"    mov rcx, rbx\n"
"rent_zero:\n"
"    test rcx, rcx\n"
"    jz rent_done\n"
"    mov byte ptr [r13], 0\n"
"    inc r13\n"
"    dec rcx\n"
"    jmp rent_zero\n"
"rent_done:\n"
"    lea rax, [r12 + 32]\n"
"    pop r13\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"rent_bad_size:\n"
"    lea rdi, [rip + _rt_err_heap_bad_size]\n"
"    jmp rt_error_exit\n"
"rent_oom:\n"
"    lea rdi, [rip + _rt_err_heap_oom]\n"
"    jmp rt_error_exit\n"
"\n"
"moveOut:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    push r12\n"
"    push r13\n"
"    test rdi, rdi\n"
"    jz moveOut_invalid\n"
"    mov r12, rdi\n"
"    lea rbx, [rdi - 32]\n"
"    mov eax, dword ptr [rbx]\n"
"    cmp eax, 0xDEADBEEF\n"
"    jne moveOut_invalid\n"
"    mov rdi, r12\n"
"    call rt_heap_block_lock\n"
"    mov eax, dword ptr [rbx + 12]\n"
"    test eax, eax\n"
"    jz moveOut_double_unlock\n"
"    mov dword ptr [rbx + 12], 0\n"
"    mov rcx, qword ptr [rbx + 4]\n"
"    mov r13, r12\n"
"moveOut_wipe:\n"
"    test rcx, rcx\n"
"    jz moveOut_unmap\n"
"    mov byte ptr [r13], 0\n"
"    inc r13\n"
"    dec rcx\n"
"    jmp moveOut_wipe\n"
"moveOut_unmap:\n"
"    mov rdi, r12\n"
"    call rt_heap_block_unlock\n"
"    mov rdi, rbx\n"
"    call _free\n"
"    xor eax, eax\n"
"    pop r13\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"moveOut_invalid:\n"
"    lea rdi, [rip + _rt_err_heap_invalid]\n"
"    jmp rt_error_exit\n"
"moveOut_double_unlock:\n"
"    mov rdi, r12\n"
"    call rt_heap_block_unlock\n"
"moveOut_double:\n"
"    lea rdi, [rip + _rt_err_heap_double_free]\n"
"    jmp rt_error_exit\n"
"\n"
"PeekByte:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    push r12\n"
"    mov edx, 1\n"
"    call rt_heap_bounds_check\n"
"    mov r12, rax\n"
"    mov rdi, r12\n"
"    call rt_heap_block_lock\n"
"    lea rbx, [r12 - 32]\n"
"    mov eax, dword ptr [rbx + 12]\n"
"    test eax, eax\n"
"    jz rt_heap_block_dead\n"
"    lea rax, [r12 + rsi]\n"
"    movzx eax, byte ptr [rax]\n"
"    mov ebx, eax\n"
"    mov rdi, r12\n"
"    call rt_heap_block_unlock\n"
"    mov eax, ebx\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"PokeByte:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    push r12\n"
"    push r13\n"
"    mov r13d, edx\n"
"    mov edx, 1\n"
"    call rt_heap_bounds_check\n"
"    mov r12, rax\n"
"    mov rdi, r12\n"
"    call rt_heap_block_lock\n"
"    lea rbx, [r12 - 32]\n"
"    mov eax, dword ptr [rbx + 12]\n"
"    test eax, eax\n"
"    jz rt_heap_block_dead\n"
"    lea rax, [r12 + rsi]\n"
"    mov byte ptr [rax], r13b\n"
"    mov rdi, r12\n"
"    call rt_heap_block_unlock\n"
"    xor eax, eax\n"
"    pop r13\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"PeekInt:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    push r12\n"
"    mov edx, 4\n"
"    call rt_heap_bounds_check\n"
"    mov r12, rax\n"
"    mov rdi, r12\n"
"    call rt_heap_block_lock\n"
"    lea rbx, [r12 - 32]\n"
"    mov eax, dword ptr [rbx + 12]\n"
"    test eax, eax\n"
"    jz rt_heap_block_dead\n"
"    lea rax, [r12 + rsi]\n"
"    mov eax, dword ptr [rax]\n"
"    mov ebx, eax\n"
"    mov rdi, r12\n"
"    call rt_heap_block_unlock\n"
"    mov eax, ebx\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"PokeInt:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    push r12\n"
"    push r13\n"
"    mov r13d, edx\n"
"    mov edx, 4\n"
"    call rt_heap_bounds_check\n"
"    mov r12, rax\n"
"    mov rdi, r12\n"
"    call rt_heap_block_lock\n"
"    lea rbx, [r12 - 32]\n"
"    mov eax, dword ptr [rbx + 12]\n"
"    test eax, eax\n"
"    jz rt_heap_block_dead\n"
"    lea rax, [r12 + rsi]\n"
"    mov dword ptr [rax], r13d\n"
"    mov rdi, r12\n"
"    call rt_heap_block_unlock\n"
"    xor eax, eax\n"
"    pop r13\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"AddInt:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    push r12\n"
"    push r13\n"
"    mov r13d, edx\n"
"    mov edx, 4\n"
"    call rt_heap_bounds_check\n"
"    mov r12, rax\n"
"    mov rdi, r12\n"
"    call rt_heap_block_lock\n"
"    lea rbx, [r12 - 32]\n"
"    mov eax, dword ptr [rbx + 12]\n"
"    test eax, eax\n"
"    jz rt_heap_block_dead\n"
"    lea rax, [r12 + rsi]\n"
"    mov eax, dword ptr [rax]\n"
"    add eax, r13d\n"
"    mov dword ptr [r12 + rsi], eax\n"
"    mov ebx, eax\n"
"    mov rdi, r12\n"
"    call rt_heap_block_unlock\n"
"    mov eax, ebx\n"
"    pop r13\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"rt_heap_block_dead:\n"
"    mov rdi, r12\n"
"    call rt_heap_block_unlock\n"
"    lea rdi, [rip + _rt_err_heap_invalid]\n"
"    jmp rt_error_exit\n"
"\n"
".extern _memcpy\n"
".extern _memset\n"
"\n"
"Memcpy:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    push r12\n"
"    push r13\n"
"    mov r12, rdi\n"
"    mov r13, rsi\n"
"    mov ebx, edx\n"
"    test ebx, ebx\n"
"    jz memcpy_done\n"
"    mov rsi, 0\n"
"    mov edx, ebx\n"
"    mov rdi, r12\n"
"    call rt_heap_bounds_check\n"
"    mov rsi, 0\n"
"    mov edx, ebx\n"
"    mov rdi, r13\n"
"    call rt_heap_bounds_check\n"
"    mov rdi, r12\n"
"    mov rsi, r13\n"
"    movsxd rdx, ebx\n"
"    call _memcpy\n"
"memcpy_done:\n"
"    xor eax, eax\n"
"    pop r13\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"Memset:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    push r12\n"
"    push r13\n"
"    push r14\n"
"    push r15\n"
"    mov r12, rdi\n"
"    mov r13d, edx\n"
"    movzx r15d, sil\n"
"    test r13d, r13d\n"
"    jz memset_done\n"
"    mov rsi, 0\n"
"    mov edx, r13d\n"
"    mov rdi, r12\n"
"    call rt_heap_bounds_check\n"
"    mov rdi, r12\n"
"    call rt_heap_block_lock\n"
"    lea rbx, [r12 - 32]\n"
"    mov eax, dword ptr [rbx + 12]\n"
"    test eax, eax\n"
"    jz rt_heap_block_dead\n"
"    mov r14, r12\n"
"    mov ecx, r13d\n"
"memset_loop:\n"
"    test ecx, ecx\n"
"    jz memset_unlock\n"
"    mov byte ptr [r14], r15b\n"
"    inc r14\n"
"    dec ecx\n"
"    jmp memset_loop\n"
"memset_unlock:\n"
"    mov rdi, r12\n"
"    call rt_heap_block_unlock\n"
"memset_done:\n"
"    xor eax, eax\n"
"    pop r15\n"
"    pop r14\n"
"    pop r13\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"RentGrow:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    push r12\n"
"    push r13\n"
"    push r14\n"
"    push r15\n"
"    test rdi, rdi\n"
"    jz rentgrow_invalid\n"
"    mov r14, rdi\n"
"    mov r15d, esi\n"
"    test r15d, r15d\n"
"    jz rentgrow_bad_size\n"
"    cmp r15d, 1048576\n"
"    jg rentgrow_bad_size\n"
"    lea rbx, [r14 - 32]\n"
"    mov eax, dword ptr [rbx]\n"
"    cmp eax, 0xDEADBEEF\n"
"    jne rentgrow_invalid\n"
"    mov r13, qword ptr [rbx + 4]\n"
"    mov edi, r15d\n"
"    call rent\n"
"    mov r12, rax\n"
"    mov rdx, r13\n"
"    movsxd rcx, r15d\n"
"    cmp rdx, rcx\n"
"    jle rentgrow_copy_len_ok\n"
"    mov rdx, rcx\n"
"rentgrow_copy_len_ok:\n"
"    test rdx, rdx\n"
"    jz rentgrow_free_old\n"
"    mov rdi, r12\n"
"    mov rsi, r14\n"
"    call _memcpy\n"
"rentgrow_free_old:\n"
"    mov rdi, r14\n"
"    call moveOut\n"
"    mov rax, r12\n"
"    jmp rentgrow_done\n"
"rentgrow_invalid:\n"
"    lea rdi, [rip + _rt_err_heap_invalid]\n"
"    jmp rt_error_exit\n"
"rentgrow_bad_size:\n"
"    lea rdi, [rip + _rt_err_heap_bad_size]\n"
"    jmp rt_error_exit\n"
"rentgrow_done:\n"
"    pop r15\n"
"    pop r14\n"
"    pop r13\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"AdrLo:\n"
"    ret\n"
"\n"
"AdrHi:\n"
"    shr rax, 32\n"
"    ret\n"
"\n"
"# ---- Threading (dupe / join) and timer ----\n"
".extern _pthread_create\n"
".extern _pthread_attr_init\n"
".extern _pthread_attr_setstacksize\n"
".extern _pthread_attr_destroy\n"
".extern _malloc\n"
".extern _free\n"
".extern _gettimeofday\n"
"\n"
".section __DATA,__data\n"
".p2align 3\n"
"rt_dupe_count:\n"
"    .quad 0\n"
"rt_dupe_slots:\n"
"    .space 512\n"
"rt_dupe_done:\n"
"    .space 64\n"
"\n"
".section .data\n"
"_newline:\n"
"    .byte 0x0a\n"
"\n"
".text\n"
"\n"
"timer:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    sub rsp, 32\n"
"    lea rdi, [rbp - 16]\n"
"    xor esi, esi\n"
"    call _gettimeofday\n"
"    mov rax, qword ptr [rbp - 16]\n"
"    mov ecx, dword ptr [rbp - 8]\n"
"    imul rax, 1000\n"
"    imul rax, 1000\n"
"    add rax, rcx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"rt_dupe_trampoline:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    push r12\n"
"    push r13\n"
"    mov r12, rdi\n"
"    mov rax, qword ptr [r12]\n"
"    mov rdi, qword ptr [r12 + 8]\n"
"    call rax\n"
"    mov r13, qword ptr [r12 + 16]\n"
"    lea rbx, [rip + rt_dupe_done]\n"
"    add rbx, r13\n"
"    mov byte ptr [rbx], 1\n"
"    mov rdi, r12\n"
"    call _free\n"
"    xor eax, eax\n"
"    pop r13\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"rt_dupe_spawn:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    push r12\n"
"    push r13\n"
"    push r15\n"
"    mov r12, rdi\n"
"    mov r13, rsi\n"
"    mov rdi, 24\n"
"    call _malloc\n"
"    mov r15, rax\n"
"    test r15, r15\n"
"    jz rt_dupe_spawn_fail\n"
"    mov qword ptr [r15], r12\n"
"    mov qword ptr [r15 + 8], r13\n"
"    lea rax, [rip + rt_dupe_count]\n"
"    mov rbx, qword ptr [rax]\n"
"    cmp rbx, 64\n"
"    jge rt_dupe_spawn_fail\n"
"    lea rcx, [rbx + 1]\n"
"    mov qword ptr [rax], rcx\n"
"    mov qword ptr [r15 + 16], rbx\n"
"    lea rdi, [rip + rt_dupe_slots]\n"
"    shl rbx, 3\n"
"    add rdi, rbx\n"
"    xor esi, esi\n"
"    lea rdx, [rip + rt_dupe_trampoline]\n"
"    mov rcx, r15\n"
"    call _pthread_create\n"
"    mov ebx, eax\n"
"    test ebx, ebx\n"
"    jnz rt_dupe_spawn_fail\n"
"    mov eax, dword ptr [r15 + 16]\n"
"    jmp rt_dupe_spawn_done\n"
"rt_dupe_spawn_fail:\n"
"    test r15, r15\n"
"    jz rt_dupe_spawn_done\n"
"    mov rdi, r15\n"
"    call _free\n"
"    mov eax, -1\n"
"rt_dupe_spawn_done:\n"
"    pop r15\n"
"    pop r13\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n"
"\n"
"join:\n"
"    push rbp\n"
"    mov rbp, rsp\n"
"    push rbx\n"
"    push r12\n"
"    movsxd r12, edi\n"
"    cmp r12, 0\n"
"    jl join_bad\n"
"    cmp r12, 64\n"
"    jge join_bad\n"
"    lea rbx, [rip + rt_dupe_done]\n"
"    add rbx, r12\n"
"join_wait:\n"
"    movzx eax, byte ptr [rbx]\n"
"    test al, al\n"
"    jz join_wait\n"
"    xor eax, eax\n"
"    jmp join_done\n"
"join_bad:\n"
"    mov eax, -1\n"
"join_done:\n"
"    pop r12\n"
"    pop rbx\n"
"    mov rsp, rbp\n"
"    pop rbp\n"
"    ret\n";
#define assembly_bootstrap_x86_64_len (sizeof(assembly_bootstrap_x86_64) - 1)
