static const char assembly_bootstrap_aarch64[] =
"HelloWorld:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    sub sp, sp, #32\n"
"    mov x6, x0\n"
"    bl strlen\n"
"    mov x2, x0\n"
"    mov x1, x6\n"
"    mov x16, #4\n"
"    mov x0, #1\n"
"    svc #0\n"
"\n"
"    mov x16, #1\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"strlen:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    mov w1, #0\n"
"    mov x3, x0\n"
"    cbz x3, strlenend\n"
"\n"
"strlenloop:\n"
"    ldrb w2, [x3, w1, uxtw #0]\n"
"    cmp w2, #0\n"
"    beq strlenend\n"
"    add w1, w1, #1\n"
"    b strlenloop\n"
"\n"
"strlenend:\n"
"    mov x0, x1\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"itos:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    sub sp, sp, #32\n"
"    mov x2, sp\n"
"    add x3, x2, #31\n"
"    strb wzr, [x3]\n"
"itos_loop:\n"
"    mov w4, #10\n"
"    udiv w5, w0, w4\n"
"    msub w6, w5, w4, w0\n"
"    add w6, w6, #48\n"
"    sub x3, x3, #1\n"
"    strb w6, [x3]\n"
"    mov w0, w5\n"
"    cbnz w0, itos_loop\n"
"    mov x0, x3\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"HelloWorldLine:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    sub sp, sp, #16\n"
"    mov w0, #0x0a\n"
"    strb w0, [sp]\n"
"    strb wzr, [sp, #1]\n"
"    mov x0, sp\n"
"    bl HelloWorld\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"return_statement:\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
".section __DATA,__bss\n"
".p2align 4\n"
"_str_buf: .space 4096\n"
"_str_buf0: .space 512\n"
"_str_buf1: .space 512\n"
"_str_buf2: .space 512\n"
"_str_buf3: .space 512\n"
"_str_buf4: .space 512\n"
"_str_buf5: .space 512\n"
"\n"
".text\n"
"BigWord:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x19, x20, [sp, #-16]!\n"
"    stp x21, x22, [sp, #-16]!\n"
"    mov x19, x0\n"
"    mov x20, x1\n"
"    bl strlen\n"
"    mov x21, x0\n"
"    mov x0, x20\n"
"    bl strlen\n"
"    add x2, x21, x0\n"
"    add x2, x2, #1\n"
"    adrp x3, _str_buf0@PAGE\n"
"    add x3, x3, _str_buf0@PAGEOFF\n"
"    mov x0, x3\n"
"    mov x1, x19\n"
"    mov x4, #0\n"
"BigWord_copy1:\n"
"    cmp x4, x21\n"
"    b.ge BigWord_copy2\n"
"    ldrb w5, [x1, x4]\n"
"    strb w5, [x3, x4]\n"
"    add x4, x4, #1\n"
"    b BigWord_copy1\n"
"BigWord_copy2:\n"
"    mov x1, x20\n"
"    mov x4, #0\n"
"BigWord_copy2_loop:\n"
"    ldrb w5, [x1, x4]\n"
"    cbz w5, BigWord_done\n"
"    add x6, x3, x21\n"
"    strb w5, [x6, x4]\n"
"    add x4, x4, #1\n"
"    b BigWord_copy2_loop\n"
"BigWord_done:\n"
"    add x6, x3, x21\n"
"    strb wzr, [x6, x4]\n"
"    mov x0, x3\n"
"    ldp x21, x22, [sp], #16\n"
"    ldp x19, x20, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"SmolString:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    mov x6, x0\n"
"    mov w7, w1\n"
"    mov w8, w2\n"
"    sub w9, w8, w7\n"
"    adrp x3, _str_buf1@PAGE\n"
"    add x3, x3, _str_buf1@PAGEOFF\n"
"    mov x4, #0\n"
"SmolString_loop:\n"
"    cmp w4, w9\n"
"    b.ge SmolString_end\n"
"    add x5, x7, x4\n"
"    ldrb w10, [x6, x5]\n"
"    strb w10, [x3, x4]\n"
"    add w4, w4, #1\n"
"    b SmolString_loop\n"
"SmolString_end:\n"
"    strb wzr, [x3, x4]\n"
"    mov x0, x3\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"CharAt:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    adrp x3, _str_buf2@PAGE\n"
"    add x3, x3, _str_buf2@PAGEOFF\n"
"    ldrb w4, [x0, x1]\n"
"    strb w4, [x3]\n"
"    strb wzr, [x3, #1]\n"
"    mov x0, x3\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"Change:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x23, x24, [sp, #-16]!\n"
"    stp x19, x20, [sp, #-16]!\n"
"    stp x21, x22, [sp, #-16]!\n"
"    mov x19, x0\n"
"    mov x20, x1\n"
"    mov x21, x2\n"
"    bl strlen\n"
"    mov x22, x0\n"
"    mov x0, x20\n"
"    bl strlen\n"
"    mov x23, x0\n"
"    mov x0, x21\n"
"    bl strlen\n"
"    mov x24, x0\n"
"    adrp x3, _str_buf3@PAGE\n"
"    add x3, x3, _str_buf3@PAGEOFF\n"
"    mov x4, #0\n"
"    mov x5, #0\n"
"Change_find:\n"
"    cmp x5, x22\n"
"    b.ge Change_nomatch\n"
"    mov x6, #0\n"
"Change_cmp:\n"
"    cmp x6, x23\n"
"    b.ge Change_found\n"
"    add x7, x19, x5\n"
"    add x7, x7, x6\n"
"    ldrb w8, [x7]\n"
"    ldrb w9, [x20, x6]\n"
"    cmp w8, w9\n"
"    b.ne Change_next\n"
"    add x6, x6, #1\n"
"    b Change_cmp\n"
"Change_next:\n"
"    add x5, x5, #1\n"
"    b Change_find\n"
"Change_found:\n"
"    mov x6, #0\n"
"Change_copy_before:\n"
"    cmp x6, x5\n"
"    b.ge Change_copy_new\n"
"    ldrb w8, [x19, x6]\n"
"    strb w8, [x3, x4]\n"
"    add x6, x6, #1\n"
"    add x4, x4, #1\n"
"    b Change_copy_before\n"
"Change_copy_new:\n"
"    mov x6, #0\n"
"Change_copy_new_loop:\n"
"    ldrb w8, [x21, x6]\n"
"    cbz w8, Change_copy_after\n"
"    strb w8, [x3, x4]\n"
"    add x6, x6, #1\n"
"    add x4, x4, #1\n"
"    b Change_copy_new_loop\n"
"Change_copy_after:\n"
"    add x5, x5, x23\n"
"Change_copy_after_loop:\n"
"    cmp x5, x22\n"
"    b.ge Change_done\n"
"    ldrb w8, [x19, x5]\n"
"    cbz w8, Change_done\n"
"    strb w8, [x3, x4]\n"
"    add x5, x5, #1\n"
"    add x4, x4, #1\n"
"    b Change_copy_after_loop\n"
"Change_done:\n"
"    strb wzr, [x3, x4]\n"
"    mov x0, x3\n"
"    ldp x21, x22, [sp], #16\n"
"    ldp x19, x20, [sp], #16\n"
"    ldp x23, x24, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"Change_nomatch:\n"
"    mov x0, x19\n"
"    ldp x21, x22, [sp], #16\n"
"    ldp x19, x20, [sp], #16\n"
"    ldp x23, x24, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"Clipper:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    mov x7, x0\n"
"    bl strlen\n"
"    mov x6, x0\n"
"    mov x8, #0\n"
"Clipper_lead:\n"
"    cmp x8, x6\n"
"    b.ge Clipper_trail\n"
"    ldrb w9, [x7, x8]\n"
"    cmp w9, #32\n"
"    b.lo Clipper_trail\n"
"    cmp w9, #32\n"
"    b.gt Clipper_trail\n"
"    add x8, x8, #1\n"
"    b Clipper_lead\n"
"Clipper_trail:\n"
"    cmp x6, #0\n"
"    b.eq Clipper_empty\n"
"    sub x10, x6, #1\n"
"Clipper_trail_loop:\n"
"    cmp x10, x8\n"
"    b.lo Clipper_copy\n"
"    ldrb w9, [x7, x10]\n"
"    cmp w9, #32\n"
"    b.lo Clipper_copy\n"
"    cmp w9, #32\n"
"    b.gt Clipper_copy\n"
"    sub x10, x10, #1\n"
"    b Clipper_trail_loop\n"
"Clipper_copy:\n"
"    adrp x3, _str_buf4@PAGE\n"
"    add x3, x3, _str_buf4@PAGEOFF\n"
"    mov x4, #0\n"
"Clipper_copy_loop:\n"
"    add x5, x8, x4\n"
"    cmp x5, x10\n"
"    b.gt Clipper_copy_done\n"
"    ldrb w9, [x7, x5]\n"
"    strb w9, [x3, x4]\n"
"    add x4, x4, #1\n"
"    b Clipper_copy_loop\n"
"Clipper_copy_done:\n"
"    strb wzr, [x3, x4]\n"
"    mov x0, x3\n"
"Clipper_ret:\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"Clipper_empty:\n"
"    mov x0, x7\n"
"    b Clipper_ret\n"
"\n"
"SmolStrings:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    stp x19, x20, [sp, #-16]!\n"
"    stp x21, x22, [sp, #-16]!\n"
"    mov x19, x0\n"
"    mov x20, x1\n"
"    bl strlen\n"
"    mov x21, x0\n"
"    mov x0, x20\n"
"    bl strlen\n"
"    mov x22, x0\n"
"    adrp x3, _str_buf5@PAGE\n"
"    add x3, x3, _str_buf5@PAGEOFF\n"
"    mov x4, #0\n"
"    mov x5, #0\n"
"    mov x6, #0\n"
"SmolStrings_loop:\n"
"    cmp x5, x21\n"
"    b.ge SmolStrings_done\n"
"    mov x7, #0\n"
"SmolStrings_cmp:\n"
"    cmp x7, x22\n"
"    b.ge SmolStrings_delim\n"
"    add x8, x5, x7\n"
"    cmp x8, x21\n"
"    b.ge SmolStrings_part\n"
"    ldrb w9, [x19, x8]\n"
"    ldrb w10, [x20, x7]\n"
"    cmp w9, w10\n"
"    b.ne SmolStrings_part\n"
"    add x7, x7, #1\n"
"    b SmolStrings_cmp\n"
"SmolStrings_delim:\n"
"    cmp x4, #0\n"
"    b.eq SmolStrings_skip_sep\n"
"    mov w9, #1\n"
"    strb w9, [x3, x4]\n"
"    add x4, x4, #1\n"
"SmolStrings_skip_sep:\n"
"    add x5, x5, x22\n"
"    b SmolStrings_loop\n"
"SmolStrings_part:\n"
"    cmp x5, x21\n"
"    b.ge SmolStrings_done\n"
"    ldrb w9, [x19, x5]\n"
"    cbz w9, SmolStrings_done\n"
"    mov x7, #0\n"
"SmolStrings_cmp2:\n"
"    cmp x7, x22\n"
"    b.ge SmolStrings_delim\n"
"    add x8, x5, x7\n"
"    cmp x8, x21\n"
"    b.ge SmolStrings_part_end\n"
"    ldrb w10, [x19, x8]\n"
"    ldrb w11, [x20, x7]\n"
"    cmp w10, w11\n"
"    b.ne SmolStrings_part_end\n"
"    add x7, x7, #1\n"
"    b SmolStrings_cmp2\n"
"SmolStrings_part_end:\n"
"    strb w9, [x3, x4]\n"
"    add x4, x4, #1\n"
"    add x5, x5, #1\n"
"    b SmolStrings_part\n"
"SmolStrings_done:\n"
"    strb wzr, [x3, x4]\n"
"    mov x0, x3\n"
"    ldp x21, x22, [sp], #16\n"
"    ldp x19, x20, [sp], #16\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"# ---- Runtime error handlers ----\n"
"\n"
"_rt_err_oob:\n"
".asciz \"Runtime Error: Array index out of bounds\\n\"\n"
".p2align 2\n"
"_rt_err_null_str:\n"
".asciz \"Runtime Error: Null string access\\n\"\n"
".p2align 2\n"
"_rt_err_div_zero:\n"
".asciz \"Runtime Error: Division by zero\\n\"\n"
".p2align 2\n"
"\n"
"rt_error_exit:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    bl strlen\n"
"    mov x2, x0\n"
"    mov x1, x6\n"
"    mov x0, #2\n"
"    mov x16, #4\n"
"    svc #0\n"
"    mov x0, #1\n"
"    mov x16, #1\n"
"    svc #0\n"
"\n"
"rt_array_bounds_check:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    cmp w0, #0\n"
"    b.lt rt_array_oob\n"
"    cmp w0, w1\n"
"    b.ge rt_array_oob\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"rt_array_oob:\n"
"    adrp x6, _rt_err_oob@PAGE\n"
"    add x6, x6, _rt_err_oob@PAGEOFF\n"
"    mov x0, x6\n"
"    b rt_error_exit\n"
"\n"
"rt_null_str_check:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    cbnz x0, rt_null_str_ok\n"
"    adrp x6, _rt_err_null_str@PAGE\n"
"    add x6, x6, _rt_err_null_str@PAGEOFF\n"
"    mov x0, x6\n"
"    b rt_error_exit\n"
"rt_null_str_ok:\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"rt_div_zero_check:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    cbnz w0, rt_div_zero_ok\n"
"    adrp x6, _rt_err_div_zero@PAGE\n"
"    add x6, x6, _rt_err_div_zero@PAGEOFF\n"
"    mov x0, x6\n"
"    b rt_error_exit\n"
"rt_div_zero_ok:\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n";
#define assembly_bootstrap_aarch64_len (sizeof(assembly_bootstrap_aarch64) - 1)
