static const char assembly_bootstrap_aarch64[] =
"HelloWorld:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    sub sp, sp, #32\n"
"    mov x6, x0\n"
"    bl strlen\n"
"    mov x2, x0\n"
"    mov x1, x6\n"
"    mov x16, #4\n"
"    mov x0, #1\n"
"    svc #0\n"
"\n"
"    mov x16, #1\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"strlen:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    mov w1, #0\n"
"    mov x3, x0\n"
"    cbz x3, strlenend\n"
"\n"
"strlenloop:\n"
"    ldrb w2, [x3, w1, uxtw #0]\n"
"    cmp w2, #0\n"
"    beq strlenend\n"
"    add w1, w1, #1\n"
"    b strlenloop\n"
"\n"
"strlenend:\n"
"    mov x0, x1\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"itos:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    sub sp, sp, #32\n"
"    mov x2, sp\n"
"    add x3, x2, #31\n"
"    strb wzr, [x3]\n"
"itos_loop:\n"
"    mov w4, #10\n"
"    udiv w5, w0, w4\n"
"    msub w6, w5, w4, w0\n"
"    add w6, w6, #48\n"
"    sub x3, x3, #1\n"
"    strb w6, [x3]\n"
"    mov w0, w5\n"
"    cbnz w0, itos_loop\n"
"    mov x0, x3\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"HelloWorldLine:\n"
"    stp x29, x30, [sp, #-16]!\n"
"    mov x29, sp\n"
"    sub sp, sp, #16\n"
"    mov w0, #0x0a\n"
"    strb w0, [sp]\n"
"    strb wzr, [sp, #1]\n"
"    mov x0, sp\n"
"    bl HelloWorld\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n"
"\n"
"return_statement:\n"
"    mov sp, x29\n"
"    ldp x29, x30, [sp], #16\n"
"    ret\n";
#define assembly_bootstrap_aarch64_len (sizeof(assembly_bootstrap_aarch64) - 1)
